<a href="https://colab.research.google.com/github/nandinisingh16/fakenews/blob/main/fakenews_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd


In [2]:
df=pd.read_csv('FakeNewsNet.csv')

In [3]:
df.head()

title  \
0  Kandi Burruss Explodes Over Rape Accusation on...   
1  People's Choice Awards 2018: The best red carp...   
2  Sophia Bush Sends Sweet Birthday Message to 'O...   
3  Colombian singer Maluma sparks rumours of inap...   
4  Gossip Girl 10 Years Later: How Upper East Sid...   

                                            news_url        source_domain  \
0  http://toofab.com/2017/05/08/real-housewives-a...           toofab.com   
1  https://www.today.com/style/see-people-s-choic...        www.today.com   
2  https://www.etonline.com/news/220806_sophia_bu...     www.etonline.com   
3  https://www.dailymail.co.uk/news/article-33655...  www.dailymail.co.uk   
4  https://www.zerchoo.com/entertainment/gossip-g...      www.zerchoo.com   

   tweet_num  real  
0         42     1  
1          0     1  
2         63     1  
3         20     1  
4         38     1

In [4]:
df.shape

(23196, 5)

In [5]:
df.isnull().sum()

title              0
news_url         330
source_domain    330
tweet_num          0
real               0
dtype: int64

In [6]:
###Drop Nan Values
df=df.dropna()


In [8]:
df.head()

title  \
0  Kandi Burruss Explodes Over Rape Accusation on...   
1  People's Choice Awards 2018: The best red carp...   
2  Sophia Bush Sends Sweet Birthday Message to 'O...   
3  Colombian singer Maluma sparks rumours of inap...   
4  Gossip Girl 10 Years Later: How Upper East Sid...   

                                            news_url        source_domain  \
0  http://toofab.com/2017/05/08/real-housewives-a...           toofab.com   
1  https://www.today.com/style/see-people-s-choic...        www.today.com   
2  https://www.etonline.com/news/220806_sophia_bu...     www.etonline.com   
3  https://www.dailymail.co.uk/news/article-33655...  www.dailymail.co.uk   
4  https://www.zerchoo.com/entertainment/gossip-g...      www.zerchoo.com   

   tweet_num  real  
0         42     1  
1          0     1  
2         63     1  
3         20     1  
4         38     1

In [9]:
## Get the Independent Features

X=df.drop('real',axis=1)

## Get the Dependent features
y=df['real']

In [11]:
X.shape

(22866, 4)

In [12]:

y.shape

(22866,)

In [13]:
import tensorflow as tf

In [14]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [15]:
### Vocabulary size
voc_size=5000

One hot encodding

In [16]:
messages=X.copy()
messages['title'][1]


"People's Choice Awards 2018: The best red carpet looks"

In [17]:
import nltk
import re
from nltk.corpus import stopwords

In [18]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [20]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer ##stemming purpose
ps = PorterStemmer()
corpus = []

# Reset the index of the messages DataFrame
messages.reset_index(inplace=True)

for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [21]:
corpus

['kandi burruss explod rape accus real housew atlanta reunion video',
 'peopl choic award best red carpet look',
 'sophia bush send sweet birthday messag one tree hill co star hilari burton breyton eva',
 'colombian singer maluma spark rumour inappropri relationship aunt',
 'gossip girl year later upper east sider shock world chang pop cultur forev',
 'gwen stefani got dump blake shelton jealousi drama exclus',
 'broward counti sheriff fire lie parkland',
 'amber rose shut french montana date rumor call rapper bruvaaa',
 'mindi kale make first post babi appear disneyland wrinkl time co star',
 'katharin mcphee butcher toni nomin drink',
 'wag miami star ashley nicol robert philip wheeler marri',
 'mel gibson hollywood pedophil nowher left hide',
 'medium tyler henri address chill messag kristin cavallari deceas brother express read',
 'dwt season result week disney night',
 'reason tarek el moussa overcom latest back injuri',
 'david cassidi cut estrang daughter kati complet leav son b

In [22]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[4794, 3730, 4377, 1237, 3791, 4381, 829, 4271, 4863, 4173],
 [2413, 3367, 649, 2206, 4452, 2681, 269],
 [1222,
  4230,
  1484,
  1799,
  910,
  4710,
  1507,
  2103,
  4591,
  334,
  2818,
  4732,
  4296,
  3163,
  1580],
 [2115, 4237, 3420, 4911, 4621, 4150, 3688, 4850],
 [3529, 3902, 3062, 3197, 4216, 4923, 454, 4620, 3890, 4470, 131, 3544, 799],
 [3524, 3414, 4690, 3982, 489, 1809, 3373, 4462, 942],
 [4778, 2393, 4183, 621, 553, 8],
 [4881, 331, 64, 890, 4074, 2195, 3898, 3174, 1714, 2483],
 [764, 860, 1845, 2187, 2594, 4236, 1539, 832, 2608, 356, 334, 2818],
 [3680, 4104, 1528, 3773, 1350, 3983],
 [262, 183, 2818, 3236, 1084, 3861, 1615, 2169, 250],
 [3374, 1158, 3936, 3617, 2058, 1501, 4635],
 [4458, 1814, 3685, 841, 3931, 4710, 695, 535, 2792, 4582, 271, 728],
 [1650, 1791, 3844, 278, 259, 4771],
 [1775, 3915, 2163, 545, 2035, 2808, 488, 1838],
 [206, 3855, 4653, 1223, 1384, 2886, 3682, 684, 1593, 4810],
 [2060, 3011, 1796, 2592, 667, 1800, 2188],
 [3410, 2098, 4678, 2180, 870,

Embedding

In [23]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[4794 3730 4377 ...    0    0    0]
 [2413 3367  649 ...    0    0    0]
 [1222 4230 1484 ...    0    0    0]
 ...
 [ 220  168 1269 ...    0    0    0]
 [4124 4533 4972 ...    0    0    0]
 [2862 4584 4788 ...    0    0    0]]


In [24]:
## Creating model
embedding_vector_features=40 ##features representation
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [25]:
len(embedded_docs),y.shape

(22866, (22866,))

In [26]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

model training


In [28]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.7800 - loss: 0.5370 - val_accuracy: 0.8305 - val_loss: 0.4046
Epoch 2/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 7s 30ms/step - accuracy: 0.8450 - loss: 0.3581 - val_accuracy: 0.8313 - val_loss: 0.3958
Epoch 3/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 12s 38ms/step - accuracy: 0.8810 - loss: 0.3024 - val_accuracy: 0.8158 - val_loss: 0.4095
Epoch 4/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 9s 36ms/step - accuracy: 0.8839 - loss: 0.2940 - val_accuracy: 0.8202 - val_loss: 0.4283
Epoch 5/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 9s 36ms/step - accuracy: 0.8912 - loss: 0.2728 - val_accuracy: 0.8129 - val_loss: 0.4418
Epoch 6/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.9018 - loss: 0.2563 - val_accuracy: 0.8081 - val_loss: 0.4463
Epoch 7/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 20s 46ms/step - accuracy: 0.9046 - loss: 0.2404 - val_accuracy: 0.7925 - val_loss: 0.4930
Epoch 8/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 11s 45ms/step - accuracy: 0.9054 - loss: 0.2263 - val

Adding dropout

In [29]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [30]:
y_pred=model.predict(X_test)

236/236 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step


In [31]:
y_pred=np.where(y_pred > 0.6, 1,0) ##AUC ROC Curve

In [32]:
from sklearn.metrics import confusion_matrix

In [33]:
confusion_matrix(y_test,y_pred)

array([[1842,    0],
       [5704,    0]])

In [34]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)



0.24410283593957063

In [35]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.24      1.00      0.39      1842
           1       0.00      0.00      0.00      5704

    accuracy                           0.24      7546
   macro avg       0.12      0.50      0.20      7546
weighted avg       0.06      0.24      0.10      7546



/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
